### ISSUE TITLE
Meshes saved with ssbh_data_py are correctly previewed in CrossMod + StudioSB but not in Ultimate

### ISSUE THREAD

**Issue by ssbucarlos** [ScanMountGoat/ssbh_data_py#14]
Screenshots taken with a test model with minor modifications.

Crossmod preview
![image](https://user-images.githubusercontent.com/77519735/131925030-88c536ac-2e98-4c88-94f9-a751f358750f.png)

.numshb exported from Blender -> Ultimate
![2021090215424000-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/77519735/131923443-7aafcdb5-effe-49f0-9c29-7f800007cc70.jpg)

.numshb exported from Blender -> StudioSB -> Ultimate
![2021090215292400-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/77519735/131923702-bf5a6b01-e0f7-480c-9d27-348400967025.jpg)

The only difference i can really see is that the vanilla and studiosb .numshb use an array of HalfFloats but the ssbh_data_py output is using Float3. The stride0 seems to be correctly compensated so im not sure if this is truly the reason.
![image](https://user-images.githubusercontent.com/77519735/131924392-7a570927-5fdf-46e2-b59c-7b004c149c8f.png)

idk how to attach files on github but heres the .numshb files but i added .txt to them
[model.numshb.txt](https://github.com/ScanMountGoat/ssbh_data_py/files/7102143/model.numshb.txt)

[studio_sb_model.numshb.txt](https://github.com/ScanMountGoat/ssbh_data_py/files/7102141/studio_sb_model.numshb.txt)

Thanks in advance for looking into this :)

**Comment by ScanMountGoat** [comment]
I'm pretty sure I've fixed this bug already since I'm not able to reproduce this on the Rust side. The changes might not have been applied to the ssbh_data_py. I'll double check and let you know once it's updated.

**Comment by ScanMountGoat** [comment]
I'm not getting any issues with Float3 for normals. You can attach files as a zip.
![image](https://user-images.githubusercontent.com/23301691/131927420-3611ac48-f6d8-4662-a67e-36df89ebe92e.png)

**Comment by ScanMountGoat** [comment]
Doing a JSON comparison of the two files you uploaded, I noticed that a lot of the vertex weight arrays are missing from model.numshb compared to the StudioSB mesh.

**Comment by ScanMountGoat** [comment]
As a sanity check, you can do `read_mesh(...)` followed immediately by `mesh.save()` from Blender and see if you're still having the same issue. If that works, there might be something missing from your exporter.

**Comment by ssbucarlos** [comment]
Thank you for looking into this :) I didnt think to do the sanity check, ill try that out rn and ill keep it in mind in the future as well for troubleshooting

**Comment by ssbucarlos** [comment]
I might just have an out-of-date version, since the sanity check via IDLE was successful, but the sanity check from blender was not. Interestingly re-exporting my blender outputed numshb file by using ssbh_data_py from IDLE worked.  Comparing the blender outputted numshb with the re-export from IDLE, it seems like the issue is that the final_buffer_offset was always stuck to 0. Thank you for helping resolve this :)
