### ISSUE TITLE
Parsed anims contain 'NaN' for rotation values.

### ISSUE THREAD

**Issue by ssbucarlos** [ScanMountGoat/ssbh_data_py#17]
[j02win2.zip](https://github.com/ScanMountGoat/ssbh_data_py/files/7206742/j02win2.zip)
Hello, so recently i discovered that when parsing 'fighter/lucina/motion/body/c00/j02win2.nuanmb', some of the values in the rotation array is NaN. 
![image](https://user-images.githubusercontent.com/77519735/134260104-f00ad1d8-8f4f-46eb-aafd-40db656b27b8.png)
i am running version 0.3.4 (i think this is how i check tbh not sure lol)
![image](https://user-images.githubusercontent.com/77519735/134260135-9a8c971b-8d57-4d03-826b-e4c75272a80d.png)
Thanks in advance for looking into this :)

**Comment by ScanMountGoat** [comment]
The code is probably taking the square root of a negative number. I have a few other compression related changes to finish up before this will be fixed. Thanks for the detailed steps to reproduce the issue.

**Comment by ssbucarlos** [comment]
Oh cool glad to see that you know where the issue probably lies. Take ur time with the fix, theres no rush 😃

**Comment by ScanMountGoat** [comment]
This is fixed in ssbh_data now, so the changes will eventually make their way to ssbh_data_py. The issue was a square root of a negative number for non unit quaternions. Those NaN values will be calculated as 0.0. I'll look into handling it more robustly at some point.

**Comment by ScanMountGoat** [comment]
This is now fixed on master. There are a number of inaccuracies with how scaling is handled that have been inherited from C#, so I would recommend waiting for the next official release before updating.
