### ISSUE TITLE
Billboard flag for bone class

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_data_py#30]
The bone class should have an attribute to indicate what type of billboarding if any it uses, similar to ssbh_lib_json. (Sample from Pac-Man's apple NUSKTB)
```json
{
          "name": "Have",
          "index": 2,
          "parent_index": 1,
          "flags": {
            "unk1": 1,
            "billboard_type": "None"
          }
        },
        {
          "name": "PacmanappleN",
          "index": 3,
          "parent_index": 2,
          "flags": {
            "unk1": 1,
            "billboard_type": "XYAxial"
          }
        }
```

**Comment by ScanMountGoat** [comment]
This needs an update to ssbh_data as well. Once I double check the flags, this should be straightforward to implement.

**Comment by ScanMountGoat** [comment]
This is implemented on the latest commit and should be in the next release.
