### ISSUE TITLE
A method of combining two mesh objects

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_data_py#38]
So I was attempting to combine to two mesh objects into one but I was running into issues. The position data was correct, but the normals, tangents, bitangents, and UV's were messed up. The reason I was doing this is to get the same effect as Kirby's Game and Watch pan, which uses vertex order to render the handle last. (Shown in first two images)  I confirmed this after getting the opposite effect by reversing vertex_indices.  (Shown in third image) The ZIP has the pan's vanilla files and my attempt at a combining script (too long to post here).

[copy_gamewatch_pan.zip](https://github.com/ScanMountGoat/ssbh_data_py/files/8485913/copy_gamewatch_pan.zip)

<img src="https://user-images.githubusercontent.com/6856627/163304024-46268a32-6656-4e4d-86ed-11fbc98b3029.png" height="300" />
<img src="https://user-images.githubusercontent.com/6856627/163304061-bc5cb563-7bfe-4b0e-b0d9-061cc3c40dc1.png" width="150" />
<img src="https://media.discordapp.net/attachments/686241052251783168/961455140156612628/unknown.png" width="200" />

**Comment by ScanMountGoat** [comment]
What files are you running the script with? The reason the model is effected by "vertex order" is because writes to the depth buffer are disabled for most of Game and Watch's meshes by setting `o.disable_depth_write = True`. The order normally doesn't matter because of depth writes and depth testing. If you have depth writes disabled, the faces that are rendered last will appear in front.

**Comment by ScanMountGoat** [comment]
If you want to reverse the render order of vertices, make sure to reverse the order of the faces and not the entire vertex index list. The winding order is important for face culling or if you want to calculate new normals. If you want to reverse indices `[0, 1, 2, 3, 4, 5]` you would get `[3, 4, 5, 0, 1, 2]`.

**Comment by zrksyd** [comment]
Oh thank you. I had no clue that o.disable_depth_write attribute was a thing. When reversing vertex indices, is it always in groups of three?

**Comment by ScanMountGoat** [comment]
Yeah. You can assume each face is 3 consecutive indices for Smash Ultimate.
