### ISSUE TITLE
support for matl version 1.5

### ISSUE THREAD

**Issue by AkaiiKitsune** [ScanMountGoat/ssbh_data_py#47]
Hey there !

I was wondering. I'm trying to import files from a dump of the arcade game taiko nijiiro, that uses lumen files. 
Everything works besides material import (since it uses numatb version 1.5). 

It's completely unrelated to smash in particular but do you happen to have documentation or ideas on how i could add support for those?
Thanks a ton !

**Comment by ScanMountGoat** [comment]
I checked and it looks like ssbh_lib supports version v1.5 but ssbh_data does not. I've made an issue for this in https://github.com/ultimate-research/ssbh_lib/issues/153. ssbh_data_py is based off of ssbh_data, so it doesn't support v1.5 yet. It looks like the rasterizer and blend state structs for the older version are completely undocumented.

If you don't need Python, you can just use ssbh_lib from Rust or use ssbh_lib_json from terminal. It's a bit of a hack, but you could even call ssbh_lib_json as a process and work with the JSON data from Python.

**Comment by ScanMountGoat** [comment]
This is implemented in ssbh_data now on the latest commit. The plan is to do a minor release for ssbh_data_py that adds support for matl v1.5.
