### ISSUE TITLE
AttributeError: module 'ssbh_data_py' has no attribute 'mesh_data'

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_data_py#53]
Got a new computer and getting this error when trying to use ssbh_data_py. This happened both on Python 3.13 and 3.10.

**Comment by ScanMountGoat** [comment]
Python 3.13 isn't supported unless you compile yourself. Are you installing via pip?

**Comment by zrksyd** [comment]
Yes

**Comment by zrksyd** [comment]
I also tried installing use the WHL on GitHub but it had told me it was for the wrong version ( I did the 3.10 one for 3.10.9)

**Comment by zrksyd** [comment]
Do you have instructions for how to install manually for 3.13?

**Comment by ScanMountGoat** [comment]
https://github.com/ScanMountGoat/ssbh_data_py?tab=readme-ov-file#building

**Comment by zrksyd** [comment]
```
💥 maturin failed
  Caused by: Failed to parse Cargo.toml
  Caused by: TOML parse error at line 1, column 1
  |
1 | [workspace]
  | ^
missing field `package`
```

**Comment by ScanMountGoat** [comment]
Are you running the command in the sabh_data_py folder?

**Comment by zrksyd** [comment]
Nvm, yeah I got that sorted, now to fix all the errors from new PyO3. 🫠

**Comment by ScanMountGoat** [comment]
The migration to the latest PyO3 is not trivial. I'm handling this in #54.
