### ISSUE TITLE
Issues with old script due to Numpy conversion?

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_data_py#55]
https://gist.githubusercontent.com/zrksyd/d9f9cc72a29ec0cbf979e1a0de128476/raw/8f289c09b95e628f54b351ce127e024d33493f19/PS2VertexColor.py

I have this old script that allows me to edit the red lights' colors on Pokemon Stadium 2 (stage/poke_stadium2/normal/model/stc_ring_set/model.numshb). When I open the result in SSBH Editor and view the colorSet1, the colors haven't seemed to change. Printing the colors in the console, I see that it is now using Numpy types and not sure if that is messing with things. In the ZIP I included, the vanilla file is labelled as orig-model.numshb and the output from my script is model.numshb.

[stc_ring_set.zip](https://github.com/user-attachments/files/18224228/stc_ring_set.zip)

**Comment by ScanMountGoat** [comment]
It should work the same as before if you install the version of ssbh_data_py that you used when writing the script.

**Comment by zrksyd** [comment]
It might becasue I'm using your prerelease version taht's not done yet.. Maybe I should wait for you to push a release.

**Comment by ScanMountGoat** [comment]
You can always create a virtual environment with a supported Python version and install in it using pip.

**Comment by zrksyd** [comment]
Nvm, i figured it out, also make sure to check out my PR for your pyprc fork.
